name: SOL Hourly Analysis

on:
  schedule:
    # Run every hour at minute 5 (UTC)
    - cron: '5 * * * *'
  workflow_dispatch:
    # Allow manual trigger
    inputs:
      enable_whatsapp:
        description: 'Enable WhatsApp sending'
        required: false
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  sol-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      
    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt
        uv pip install twilio python-dotenv
        
    - name: Verify dependencies
      run: |
        source .venv/bin/activate
        python -c "import openai, requests, twilio; print('✅ All dependencies installed')"
        
    - name: Run SOL Analysis
      env:
        COINALYZE_API_KEY: ${{ secrets.COINALYZE_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
        WHATSAPP_TO_NUMBER: ${{ secrets.AUTO_SEND_TO_WHATSAPP }}
        AUTO_SEND_TO_WHATSAPP: ${{ github.event.inputs.enable_whatsapp || 'true' }}
        PYTHONPATH: ${{ github.workspace }}
        PYTHONUNBUFFERED: '1'
      run: |
        source .venv/bin/activate
        echo "🚀 Starting SOL Analysis with WhatsApp: $AUTO_SEND_TO_WHATSAPP"
        python sol_hourly_analysis.py
        
    - name: Check for analysis output
      if: always()
      run: |
        echo "📊 Workflow completed at $(date)"
        if [ -f "sol_analysis_state.json" ]; then
          echo "📄 State file created"
          cat sol_analysis_state.json
        fi
        
    - name: Archive analysis results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sol-analysis-${{ github.run_number }}-${{ github.run_attempt }}
        path: |
          *.json
          *.log
          *.txt
        retention-days: 3
        
    - name: Notify on failure
      if: failure()
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
        WHATSAPP_TO_NUMBER: ${{ secrets.AUTO_SEND_TO_WHATSAPP }}
      run: |
        source .venv/bin/activate
        python -c '
        import os
        from whatsapp_sender import WhatsAppSender
        if os.getenv("WHATSAPP_TO_NUMBER", "").startswith("+"):
            sender = WhatsAppSender()
            sender.send_message("🚨 SOL Analysis Failed\n\nGitHub Actions workflow encountered an error. Check the Actions tab for details.")
            print("✅ Failure notification sent")
        else:
            print("📱 WhatsApp notifications disabled - no recipient number")
        '